// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qwpskzmpdmjtfjzjgrlr.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3cHNrem1wZG1qdGZqempncmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxODk4MDYsImV4cCI6MjA0ODc2NTgwNn0.Rz-hyfzfc8UkAtKw8nVY23LxeIFrulpZaIGRpzb24-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);